# Generated by Django 4.2.3 on 2023-11-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.FileField(default=1111, upload_to=''),
            preserve_default=False,
        ),
    ]
